#!/usr/bin/env python3
"""
_init.py — Caging deployment orchestrator.

Reads plan.yaml and deploys all users (topologically sorted: parents first).
Generates per-user config.yaml, sets up API keys, DB credentials (bcrypt),
systemd services, cagingcli, and ACLs.

Usage:
    sudo python3 _init.py                            # deploy all users from plan.yaml
    sudo python3 _init.py --user cage1               # deploy only cage1
    sudo python3 _init.py --link service root cadmin  # deploy single link
    python3 _init.py --dry-run                       # simulate, no system changes
    # --link flags: --port, --username, --password
"""

import argparse
import bcrypt
import json
import os
import secrets
import shutil
import string
import subprocess
import sys
import yaml
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
CAGING_BASE = Path("/home/caging")
SCRIPT_DIR = Path(__file__).parent.resolve()

# Detect venv Python for systemd services
def _detect_venv_python() -> str:
    """Return the Python interpreter from the current venv for systemd services."""
    # 1. If running inside a venv, use sys.executable
    if sys.prefix != sys.base_prefix:
        return sys.executable
    # 2. Check VIRTUAL_ENV environment variable
    venv = os.environ.get("VIRTUAL_ENV")
    if venv:
        candidate = Path(venv) / "bin" / "python3"
        if candidate.exists():
            return str(candidate)
    # 3. Search for a nearby .venv directory (common project structure)
    for candidate_dir in [
        SCRIPT_DIR.parent.parent / ".venv",   # project root (GenericAgent/.venv)
        SCRIPT_DIR.parent / ".venv",           # temp/.venv
        SCRIPT_DIR / ".venv",                  # caging/.venv
    ]:
        candidate = candidate_dir / "bin" / "python3"
        if candidate.exists():
            return str(candidate)
    # 4. Fall back to system python
    return shutil.which("python3") or "/usr/bin/python3"


VENV_PYTHON = _detect_venv_python()
print(f"[_init] Using Python interpreter: {VENV_PYTHON}")


CONFIG_TEMPLATE = """# Caging config — auto-generated by _init.py
service:
  name: "caging-{child_name}"
  host: "0.0.0.0"
  port: {port}
  database: "{db_path}"
  log_retention_days: 90
  callback_base_url: "http://localhost:{port}"

auth:
  rate_limit:
    per_minute: 60
    per_hour: 1000
  session_secret: "change-me-to-a-random-secret"
  api_keys:
    admin:
      role: "admin"
      system_user: "caging"
      key: "ak_live_placeholder_replace_me"

policy:
  rules_file: "policy.yaml"
  reload_on_change: true

notifications:
  websocket:
    enabled: true
    path: "/ws/notifications"
    heartbeat_interval: 30

review:
  default_reviewer: "reviewer1"
  auto_assign_after_seconds: 300

expiration:
  ttl_hours: 24
  check_interval_seconds: 60
"""

POLICY_YAML_CONTENT = """rules:
  - id: 1
    description: "Allow manager to execute cagingcli commands"
    pattern: "cagingcli *"
    allowed_users:
      - "admin"
    enabled: true
  - id: 2
    description: "Deny all other cagingcli commands by default"
    pattern: "*"
    denied_users:
      - "*"
    enabled: true
"""

# Global registry populated during deployment
user_registry: dict = {}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_plan(plan_path: str) -> tuple:
    """Load and parse plan.yaml, return (topologically_ordered_users, raw_users_dict)."""
    with open(plan_path) as f:
        data = yaml.safe_load(f)

    global_ai = data.get("ai", {})
    users_raw = data.get("users", {})

    # Merge AI config into each user (user-level overrides global)
    users = {}
    for name, attrs in users_raw.items():
        user_ai = dict(global_ai)
        user_ai.update(attrs.get("ai", {}))
        user = dict(attrs)
        user["name"] = name
        user["ai"] = user_ai
        user["parent"] = attrs.get("parent", {})
        user["children"] = attrs.get("children", [])
        user["human_login"] = attrs.get("human_login")
        user["params"] = attrs.get("params", {})
        user["mode"] = attrs.get("mode", "cage")
        user["port"] = attrs.get("port", 8000)
        users[name] = user

    # Topological sort: parents before children
    ordered = []
    added = set()

    def add_user(name):
        if name in added:
            return
        added.add(name)
        user = users.get(name)
        if user:
            parent_info = user.get("parent", {})
            parent_name = parent_info.get("user") if isinstance(parent_info, dict) else None
            if parent_name and parent_name in users and parent_name not in added:
                add_user(parent_name)
            ordered.append(user)

    for name in users:
        add_user(name)

    return ordered, users


def get_parent_url(parent_name: str, parent_port: int) -> str:
    """Build parent base URL."""
    return f"http://localhost:{parent_port}"


def create_system_user(name: str, caging_base: Path):
    """Create Linux system user for caging."""
    home = caging_base if name == "root" else caging_base / name
    if subprocess.run(["id", name], capture_output=True).returncode != 0:
        subprocess.run(
            ["useradd", "--system", "--no-create-home", "--home-dir", str(home),
             "--shell", "/bin/bash", name],
            check=True,
        )
        print(f"  System user created: {name}")
    else:
        # Ensure shell is correct even for existing users
        subprocess.run(
            ["usermod", "--shell", "/bin/bash", name],
            check=True,
        )
        print(f"  System user exists, shell updated: {name}")


def create_data_dir(name: str, data_dir: Path):
    """Create ~/.caging data directory with proper ownership."""
    data_dir.mkdir(parents=True, exist_ok=True)
    owner = "root" if name == "root" else name
    subprocess.run(["chown", f"{owner}:{owner}", str(data_dir)], check=True)
    data_dir.chmod(0o750)
    print(f"  Data dir: {data_dir}")


def generate_config_yaml(user: dict, data_dir: Path) -> dict:
    """Generate the per-user config.yaml as a dict."""
    port = user.get("port", 8000)
    child_name = user["name"]
    db_path = str(data_dir / "caging.db")

    config = yaml.safe_load(CONFIG_TEMPLATE.format(
        port=port,
        db_path=db_path,
        child_name=child_name,
    ))

    # AI section
    ai_cfg = user.get("ai", {})
    config["ai"] = {
        "provider": ai_cfg.get("provider", "openai"),
        "api_key": ai_cfg.get("api_key", ""),
        "model": ai_cfg.get("model", "deepseek-reasoner"),
        "base_url": ai_cfg.get("base_url", "https://api.deepseek.com"),
        "fallback": ai_cfg.get("fallback", "manual"),
    }

    # Parent section (if user has a parent)
    parent_info = user.get("parent", {})
    parent_name = parent_info.get("user") if isinstance(parent_info, dict) else None
    if parent_name:
        config["parent"] = {
            "enabled": True,
            "base_url": f"http://localhost:{_get_user_port(parent_name)}",
            "api_key": "",
            "timeout": 30,
            "poll_interval_seconds": 10,
        }
    else:
        config["parent"] = {
            "enabled": False,
            "base_url": "",
            "api_key": "",
            "timeout": 30,
            "poll_interval_seconds": 10,
        }

    # Params from plan.yaml
    params = user.get("params", {})
    if params:
        config["params"] = dict(params)
    parent_info = user.get("parent", {})
    if isinstance(parent_info, dict):
        parent_params = parent_info.get("param", {})
        if parent_params:
            config["parent_params"] = dict(parent_params)

    return config


def write_config_yaml(config: dict, config_path: Path, owner: str):
    """Write config.yaml and set ownership."""
    with open(config_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False)
    subprocess.run(["chown", f"{owner}:{owner}", str(config_path)], check=True)
    config_path.chmod(0o640)
    print(f"  config.yaml -> {config_path}")


def _get_user_port(username: str) -> int:
    """Fetch port for a user from the global registry."""
    return user_registry.get(username, {}).get("port", 8000)


# ---------------------------------------------------------------------------
# API key generation
# ---------------------------------------------------------------------------

API_KEY_PREFIX = "ak_live_"
API_KEY_BYTES = 24


def generate_api_key() -> tuple:
    """Generate a new API key and its bcrypt hash. Returns (plain_key, hashed_key)."""
    raw = secrets.token_hex(API_KEY_BYTES)
    plain_key = f"{API_KEY_PREFIX}{raw}"
    hashed_key = bcrypt.hashpw(plain_key.encode(), bcrypt.gensalt()).decode()
    return plain_key, hashed_key


# ---------------------------------------------------------------------------
# Database credential setup (from old_install.py)
# ---------------------------------------------------------------------------

def setup_db_credentials(data_dir: Path, username: str, password: str, db_path: str):
    """Replicates old_install.py logic: init DB, create user with bcrypt-hashed credentials."""
    sys.path.insert(0, str(SCRIPT_DIR))
    from caging import database as db

    db.init_db(db_path)

    raw_key = username
    password_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
    hashed_key = bcrypt.hashpw(raw_key.encode(), bcrypt.gensalt()).decode()

    existing = db.get_user(username)
    if existing:
        db.update_user(username, password_hash=password_hash)
        print(f"  Updated existing user: {username}")
    else:
        db.create_user(
            client_id=username,
            role="admin",
            api_key_hash=hashed_key,
            system_user=username,
        )
        db.update_user(username, password_hash=password_hash)
        print(f"  Created user: {username}")
    print(f"  DB credentials set for: {username}")


# ---------------------------------------------------------------------------
# Policy deployment
# ---------------------------------------------------------------------------

def deploy_policy(data_dir: Path, owner: str):
    """Copy default policy.yaml to user data dir."""
    policy_path = data_dir / "policy.yaml"
    with open(policy_path, "w") as f:
        f.write(POLICY_YAML_CONTENT)
    subprocess.run(["chown", f"{owner}:{owner}", str(policy_path)], check=True)
    policy_path.chmod(0o640)
    print(f"  policy.yaml -> {policy_path}")


# ---------------------------------------------------------------------------
# Caging CLI deployment
# ---------------------------------------------------------------------------

def deploy_cagingcli(data_dir: Path, child_name: str, parent_url: str, api_key: str, owner: str,
                     params: dict = None, parent_params: dict = None):
    """Deploy cagingcli.py and cagingcli.yaml (replaces inline bash in init.sh)."""
    cli_dir = data_dir / "cli"
    cli_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", f"{owner}:{owner}", str(cli_dir)], check=True)

    # Copy cagingcli.py from cli subdirectory
    src_cli = SCRIPT_DIR / "cli" / "cagingcli.py"
    if src_cli.exists():
        shutil.copy2(str(src_cli), str(cli_dir / "cagingcli.py"))
        subprocess.run(["chown", f"{owner}:{owner}", str(cli_dir / "cagingcli.py")], check=True)
        (cli_dir / "cagingcli.py").chmod(0o750)
        print(f"  cagingcli.py -> {cli_dir / 'cagingcli.py'}")
    else:
        print(f"  WARNING: cagingcli.py not found at {src_cli}, skipping")

    # Copy CLI support files (shell scripts, docs)
    for filename in ("cagingcli.md", "exec.sh", "protect.sh", "release.sh"):
        src_file = SCRIPT_DIR / "cli" / filename
        if src_file.exists():
            shutil.copy2(str(src_file), str(cli_dir / filename))
            subprocess.run(["chown", f"{owner}:{owner}", str(cli_dir / filename)], check=True)
            (cli_dir / filename).chmod(0o750)
            print(f"  {filename} -> {cli_dir / filename}")
        else:
            print(f"  WARNING: {filename} not found at {src_file}, skipping")

    # Create cagingcli.yaml
    cli_yaml_path = cli_dir / "cagingcli.yaml"
    cli_config = {
        "parent": {
            "base_url": parent_url,
            "api_key": api_key,
            "timeout": 30,
        },
        "defaults": {
            "output": "text",
        },
    }
    if params:
        cli_config["params"] = dict(params)
    if parent_params:
        cli_config["parent_params"] = dict(parent_params)
    with open(cli_yaml_path, "w") as f:
        yaml.dump(cli_config, f, default_flow_style=False)
    subprocess.run(["chown", f"{owner}:{owner}", str(cli_yaml_path)], check=True)
    cli_yaml_path.chmod(0o640)
    print(f"  cagingcli.yaml -> {cli_yaml_path}")


# ---------------------------------------------------------------------------
# Systemd service setup
# ---------------------------------------------------------------------------

SYSTEMD_TEMPLATE = """[Unit]
Description=Caging {name}
After=network.target

[Service]
Type=simple
User={name}
Group={name}
WorkingDirectory={data_dir}
ExecStart={python_path} -m uvicorn caging.app:app --host 0.0.0.0 --port {port}
Restart=on-failure
RestartSec=5
Environment=PYTHONUNBUFFERED=1
Environment=PYTHONPATH={caging_src}
Environment=CAGING_CONFIG={config_path}

[Install]
WantedBy=multi-user.target
"""


def setup_systemd_service(name: str, port: int, data_dir: Path, owner: str = "root"):
    """Create systemd service file for a caging user (replaces inline bash in init.sh).

    Uses the current venv Python and treats the caging source directory
    as a shared code base via PYTHONPATH.
    """
    python_path = VENV_PYTHON
    caging_src = str(SCRIPT_DIR)  # shared caging code source (contains caging/ package)
    config_path = str(data_dir / "config.yaml")

    svc_content = SYSTEMD_TEMPLATE.format(
        name=name,
        data_dir=str(data_dir),
        python_path=python_path,
        port=port,
        config_path=config_path,
        caging_src=caging_src,
    )

    svc_path = Path(f"/etc/systemd/system/caging@{name}.service")
    with open(svc_path, "w") as f:
        f.write(svc_content)
    svc_path.chmod(0o644)
    print(f"  systemd unit: {svc_path}")

    # Enable and (re)start
    subprocess.run(["systemctl", "daemon-reload", "-q"], check=False)
    subprocess.run(["systemctl", "enable", f"caging@{name}"], check=False)
    subprocess.run(["systemctl", "restart", f"caging@{name}"], check=False)
    print(f"  service caging@{name} started")


# ---------------------------------------------------------------------------
# ACL setup
# ---------------------------------------------------------------------------

def setup_acl(parent_name: str, child_home: Path):
    """Set ACL so parent can access child's home (replaces setfacl in init.sh)."""
    if not child_home.exists():
        print(f"  SKIP ACL: {child_home} does not exist")
        return
    try:
        subprocess.run(
            ["setfacl", "-m", f"u:{parent_name}:rx", str(child_home)],
            check=True, capture_output=True,
        )
        print(f"  ACL: {parent_name} can access {child_home}")
    except subprocess.CalledProcessError as e:
        print(f"  ACL skipped (setfacl not available?): {e.stderr.decode().strip()}")


# ---------------------------------------------------------------------------
# Main deploy function
# ---------------------------------------------------------------------------

def deploy_user(user: dict, all_users: dict):
    """Deploy one user: OS user, data dir, config, keys, DB, systemd, CLI, ACL."""
    name = user["name"]
    mode = user.get("mode", "cage")
    port = user.get("port", 8000)
    parent_info = user.get("parent", {})
    parent_name = parent_info.get("user") if isinstance(parent_info, dict) else None
    children = user.get("children", [])
    human_login = user.get("human_login")
    params = user.get("params", {})
    ai_cfg = user.get("ai", {})

    # Register this user
    user_registry[name] = user

    print(f"\n{'='*60}")
    print(f" Deploying: {name} (mode={mode}, port={port})")
    print(f"{'='*60}")

    # Paths
    child_home = CAGING_BASE if name == "root" else CAGING_BASE / name
    child_data = child_home / ".caging"
    child_config_path = child_data / "config.yaml"

    # Resolve parent
    if parent_name:
        parent_port = all_users.get(parent_name, {}).get("port", 8000)
        parent_url = f"http://localhost:{parent_port}"
        parent_data = CAGING_BASE if parent_name == "root" else CAGING_BASE / parent_name
        parent_data_path = parent_data / ".caging"
        parent_config_path = parent_data_path / "config.yaml"
    else:
        parent_url = ""
        parent_config_path = None

    # 1. Create system user
    create_system_user(name, CAGING_BASE)

    # 2. Create data directory
    create_data_dir(name, child_data)

    # 3. Config + policy (only for service mode; cage is CLI-only)
    owner = "root" if name == "root" else name
    if mode == "service":
        config = generate_config_yaml(user, child_data)
        write_config_yaml(config, child_config_path, owner)
        deploy_policy(child_data, owner)
    else:
        print(f"  (cage mode — no config.yaml/policy.yaml needed)")

    # Extract params for config files
    params = user.get("params", {})
    parent_params = {}
    if isinstance(parent_info, dict):
        parent_params = parent_info.get("param", {}) or {}

    # 4. API keys — inject child's key into parent config
    child_key = None
    if parent_name and parent_config_path and parent_config_path.exists():
        with open(parent_config_path) as f:
            parent_config = yaml.safe_load(f)
        child_key, child_key_hash = generate_api_key()
        # Add child's key to parent's api_keys
        if "auth" not in parent_config:
            parent_config["auth"] = {}
        if "api_keys" not in parent_config["auth"]:
            parent_config["auth"]["api_keys"] = {}
        parent_config["auth"]["api_keys"][name] = {
            "role": "requester",
            "system_user": name,
            "key": child_key,
        }
        with open(parent_config_path, "w") as f:
            yaml.dump(parent_config, f, default_flow_style=False)
        print(f"  API key injected into parent ({parent_name}) for child ({name})")

        # For service mode child: also inject child's own key into its config
        if mode == "service" and child_config_path.exists():
            with open(child_config_path) as f:
                child_config = yaml.safe_load(f)
            child_config["parent"]["api_key"] = child_key
            with open(child_config_path, "w") as f:
                yaml.dump(child_config, f, default_flow_style=False)
            print(f"  Child API key injected into {name} config.yaml")
    elif parent_name and parent_config_path:
        print(f"  WARNING: Parent config not found at {parent_config_path}, skipping API key injection")

    # 5. DB credentials (only for service mode)
    if mode == "service" and human_login:
        db_path = str(child_data / "caging.db")
        print(f"\n  Setting up Web UI login credentials...")
        setup_db_credentials(
            data_dir=child_data,
            username=human_login.get("username", name),
            password=human_login.get("password"),
            db_path=db_path,
        )
        # Fix ownership
        subprocess.run(["chown", f"{owner}:{owner}", db_path], check=True)

    # 6. Systemd service (only for service mode)
    if mode == "service":
        setup_systemd_service(name, port, child_data, owner=owner)

    # 7. Caging CLI deployment (only if this user has a parent to connect to)
    if parent_name:
        if child_key is None:
            child_key, _ = generate_api_key()
        deploy_cagingcli(child_data, name, parent_url, child_key, owner,
                         params=params, parent_params=parent_params)

    # 8. ACL setup
    if parent_name:
        setup_acl(parent_name, child_home)

    # 9. Recursive ownership fix for the entire .caging directory
    #    Ensures database and any runtime-created files are owned by the service user
    subprocess.run(["chown", "-R", f"{owner}:{owner}", str(child_data)], check=True)
    print(f"  Ownership fixed: {child_data} -> {owner}")

    # Summary
    print(f"\n  ✓ {name} deployed successfully")


# ---------------------------------------------------------------------------
# Service cleanup
# ---------------------------------------------------------------------------

def stop_existing_services():
    """Stop and disable existing caging services before re-deploy."""
    result = subprocess.run(
        ["systemctl", "list-units", "--type=service", "--all", "--no-legend"],
        capture_output=True, text=True,
    )
    for line in result.stdout.splitlines():
        parts = line.split()
        if not parts:
            continue
        unit = parts[0]
        if unit.startswith("caging@"):
            subprocess.run(["systemctl", "stop", unit], capture_output=True)
            print(f"  Stopped existing: {unit}")


# ---------------------------------------------------------------------------
# Nginx setup
# ---------------------------------------------------------------------------

def setup_nginx(plan_path: str, portal_port: int = 50080, dry_run: bool = False):
    """Generate nginx portal config from plan.yaml, then validate and reload.

    Creates one location per service-mode user:
      /{username} → http://localhost:{port}/ui
    """
    if not os.path.exists(plan_path):
        print(f"ERROR: Plan file not found: {plan_path}")
        sys.exit(1)

    with open(plan_path) as f:
        plan = yaml.safe_load(f)

    users = plan.get("users", {})
    # Collect service-mode users (have a web service)
    service_users = []
    for name, cfg in users.items():
        if cfg.get("mode") == "service" and cfg.get("port"):
            service_users.append((name, cfg["port"]))
    service_users.sort(key=lambda x: x[1])  # sort by port

    if not service_users:
        print("ERROR: No service-mode users found in plan.yaml")
        sys.exit(1)

    dashboard_dir = CAGING_BASE / "dashboard"
    nginx_conf = Path("/etc/nginx/sites-available/caging")
    nginx_enabled = Path("/etc/nginx/sites-enabled/caging")

    print(f"  Portal port: {portal_port}")
    print(f"  Dashboard:   {dashboard_dir}")
    print(f"  Nginx conf:  {nginx_conf}")
    print(f"  Service users:")
    for name, port in service_users:
        print(f"    /{name:10} → http://localhost:{port}/ui")

    # ── 1. Copy dashboard HTML ──────────────────────────────────────
    src_dashboard = SCRIPT_DIR / "dashboard.html"
    if not src_dashboard.exists():
        print(f"ERROR: dashboard.html not found at {src_dashboard}")
        sys.exit(1)

    if not dry_run:
        dashboard_dir.mkdir(parents=True, exist_ok=True)
        dst_index = dashboard_dir / "index.html"
        shutil.copy2(str(src_dashboard), str(dst_index))
        # Set ownership to root
        subprocess.run(["chown", "-R", "root:root", str(dashboard_dir)], check=True)
        subprocess.run(["chmod", "755", str(dashboard_dir)], check=True)
        subprocess.run(["chmod", "644", str(dst_index)], check=True)
        print(f"  [✓] Dashboard copied to {dst_index}")

    # ── 2. Build nginx config ──────────────────────────────────────
    location_blocks = []
    for name, port in service_users:
        upstream = f"http://localhost:{port}"
        block = f"""    # ── {name} panel (port {port}) ──
    location /{name} {{
        proxy_pass {upstream}/ui;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Strip /{name} prefix before passing upstream
        rewrite ^/{name}(.*)$ $1 break;
    }}
"""
        location_blocks.append(block)

    locations_text = "\n".join(location_blocks)

    config_text = f"""server {{
    listen {portal_port} default_server;
    listen [::]:{portal_port} default_server;

    server_name _;

    # Dashboard static files
    root {dashboard_dir};
    index index.html;

    # Logging
    access_log /var/log/nginx/caging_access.log;
    error_log  /var/log/nginx/caging_error.log;

{locations_text}
    # ── Static assets (for dashboard CSS/images) ──
    location /static {{
        alias {dashboard_dir}/static;
        expires 7d;
    }}

    # ── Deny access to hidden files ──
    location ~ /\\. {{
        deny all;
    }}
}}
"""

    if dry_run:
        print(f"\n=== Nginx config (dry-run) ===\n{config_text}")
        print("(Dry run complete — no changes made)")
        return

    # ── 3. Write config ────────────────────────────────────────────
    with open(str(nginx_conf), "w") as f:
        f.write(config_text)
    print(f"  [✓] Nginx config written to {nginx_conf}")

    # ── 4. Activate site ───────────────────────────────────────────
    nginx_enabled.parent.mkdir(parents=True, exist_ok=True)
    if nginx_enabled.exists() or nginx_enabled.is_symlink():
        nginx_enabled.unlink()
    nginx_enabled.symlink_to(str(nginx_conf))
    print(f"  [✓] Site enabled: {nginx_enabled} → {nginx_conf}")

    # Remove default site if it conflicts
    default_site = Path("/etc/nginx/sites-enabled/default")
    if default_site.exists():
        print("  [*] Removing default nginx site (port conflict)...")
        default_site.unlink()

    # ── 5. Validate and reload ─────────────────────────────────────
    print("  [*] Validating nginx config...")
    result = subprocess.run(["nginx", "-t"], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ✗ Nginx config validation FAILED:")
        print(result.stdout)
        print(result.stderr)
        sys.exit(1)
    print("  [✓] Nginx config valid")

    print("  [*] Reloading nginx...")
    subprocess.run(["systemctl", "reload", "nginx"],
                   capture_output=True) or subprocess.run(
        ["systemctl", "restart", "nginx"], capture_output=True)

    print(f"\n{'='*60}")
    print(f"  ✅ Caging Portal ready!")
    print(f"  🌐 http://localhost:{portal_port}")
    for name, port in service_users:
        print(f"     └── /{name:10} → http://localhost:{port}/ui")
    print(f"  📁 Dashboard: {dashboard_dir}/index.html")
    print(f"{'='*60}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Caging deployment orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--plan", default=str(SCRIPT_DIR / "plan.yaml"),
                        help="Path to plan.yaml (default: ./plan.yaml)")
    parser.add_argument("--user", nargs="+", default=None,
                        help="Deploy only specific user(s) from plan")
    parser.add_argument("--link", nargs=3, metavar=('MODE', 'PARENT', 'CHILD'),
                        help="Deploy a single parent→child link (MODE=service|cage)")
    parser.add_argument("--port", type=int, default=8000,
                        help="Port for the child service (link mode)")
    parser.add_argument("--username", default=None,
                        help="Web UI username for service mode (link mode)")
    parser.add_argument("--password", default=None,
                        help="Web UI password for service mode (link mode)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Simulate deployment (no system changes)")
    parser.add_argument("--nginx", action="store_true",
                        help="Generate nginx portal config from plan.yaml")
    parser.add_argument("--portal-port", type=int, default=50080,
                        help="Nginx portal listen port (default: 50080)")
    parser.add_argument("--restart-services", action="store_true", default=True,
                        help="Restart systemd services after deployment (default: True)")
    return parser.parse_args(argv)


def main():
    args = parse_args()

    if os.geteuid() != 0 and not args.dry_run:
        print("ERROR: Must run as root (sudo)")
        sys.exit(1)

    plan_path = args.plan
    if not os.path.exists(plan_path):
        print(f"ERROR: Plan file not found: {plan_path}")
        sys.exit(1)

    # ── Nginx mode ─────────────────────────────────────────────────
    if args.nginx:
        print(f"\n{'='*60}")
        print(" Nginx portal setup")
        print(f"{'='*60}")
        setup_nginx(plan_path, portal_port=args.portal_port, dry_run=args.dry_run)
        return

    # Always load plan.yaml for AI defaults and existing user configs
    print(f"Plan: {plan_path}")
    ordered_users, all_users = load_plan(plan_path)
    print(f"Users in deployment order: {[u['name'] for u in ordered_users]}")

    # ── Single-link mode ────────────────────────────────────────────
    if args.link:
        mode, parent_name, child_name = args.link
        print(f"\n{'='*60}")
        print(f" Single-link deploy: {mode} {parent_name} → {child_name}")
        print(f"{'='*60}")

        # AI defaults: from plan.yaml's global ai section
        plan_data = yaml.safe_load(open(plan_path))
        global_ai = plan_data.get("ai", {})
        if not global_ai.get("api_key"):
            global_ai.setdefault("api_key", "")
            global_ai.setdefault("provider", "openai")
            global_ai.setdefault("model", "deepseek-reasoner")
            global_ai.setdefault("base_url", "https://api.deepseek.com")
            global_ai.setdefault("fallback", "manual")

        # Resolve parent config: use plan.yaml entry if exists, else create one
        if parent_name in all_users:
            parent_entry = dict(all_users[parent_name])
            print(f"  Parent '{parent_name}' found in plan.yaml")
        else:
            parent_entry = {
                "name": parent_name,
                "mode": "service",
                "port": 8000,
                "parent": {"user": None},
                "children": [child_name],
                "human_login": {"username": args.username or parent_name,
                                "password": args.password or "changeit!"},
                "ai": dict(global_ai),
                "params": {},
            }
            print(f"  Parent '{parent_name}' created from defaults")

        # Create child entry
        child_entry = {
            "name": child_name,
            "mode": mode,
            "port": args.port if mode == "service" else 0,
            "parent": {"user": parent_name},
            "children": [],
            "ai": dict(global_ai),
            "params": {},
        }
        # Merge any existing plan.yaml AI config for child
        if child_name in all_users:
            child_entry["ai"] = dict(all_users[child_name].get("ai", global_ai))
        if mode == "service":
            child_entry["human_login"] = {
                "username": args.username or child_name,
                "password": args.password or "changeit!",
            }

        # Build user dict
        deploy_users = {parent_name: parent_entry, child_name: child_entry}

        if args.dry_run:
            print(f"\n  Would deploy:")
            print(f"    {parent_name}: mode={parent_entry['mode']}, port={parent_entry.get('port')}")
            print(f"    {child_name}: mode={child_entry['mode']}, port={child_entry.get('port')}")
            print(f"\n  (Dry run complete — no changes made)")
            return

        # Deploy parent first, then child
        stop_existing_services()
        deploy_user(parent_entry, deploy_users)
        deploy_user(child_entry, deploy_users)
        print(f"\n✓ Link deployed: {parent_name} → {child_name}")
        return

    # ── Plan-based mode ─────────────────────────────────────────────
    if args.user:
        ordered_users = [u for u in ordered_users if u["name"] in args.user]
        if not ordered_users:
            print(f"ERROR: No matching users found for: {args.user}")
            sys.exit(1)
        print(f"Filtered to: {[u['name'] for u in ordered_users]}")

    if args.dry_run:
        print("\n=== DRY RUN ===")
        print(f"Would deploy: {[u['name'] for u in ordered_users]}")
        for u in ordered_users:
            mode = u.get("mode", "cage")
            port = u.get("port", 8000)
            parent_info = u.get("parent", {})
            parent_name = parent_info.get("user") if isinstance(parent_info, dict) else None
            print(f"  {u['name']}: mode={mode}, port={port}, parent={parent_name}")
        print("\n(Dry run complete — no changes made)")
        return

    # Stop existing services
    stop_existing_services()

    # Deploy each user in topological order
    for user in ordered_users:
        deploy_user(user, all_users)

    # Final summary
    print(f"\n{'='*60}")
    print(f" Deployment complete")
    print(f"{'='*60}")
    for name, _ in all_users.items():
        deployed = name in [u["name"] for u in ordered_users]
        print(f"  {name}: {'✓' if deployed else '— (skipped)'}")
    print(f"\n  Start services:   systemctl start caging@<user>")
    print(f"  View logs:        journalctl -u caging@<user> -f")


if __name__ == "__main__":
    main()
